/*사용자*/
CREATE TABLE MEMBER(
	ID VARCHAR2(4000) PRIMARY KEY,
	PW VARCHAR2(1000) NOT NULL,
	NAME VARCHAR2(1000) NOT NULL,
	NICK_NAME VARCHAR2(1000) NOT NULL,
	PR CLOB,
	PROFILE_PIC VARCHAR2(4000),
	TEL VARCHAR2(1000),
	SEX VARCHAR2(100) CHECK (SEX IN ('M', 'F')),
	STATUS VARCHAR2(100) CHECK (STATUS IN ('사용', '휴먼','탈퇴보류')),
	JOINED DATE DEFAULT SYSDATE
)

/*회원등급*/
CREATE TABLE GRADE(
   GRADE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   CONSTRAINT MEMBER_GRADE_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON DELETE CASCADE,
   CONSTRAINT MEMBER_GRADE_PK PRIMARY KEY(GRADE, ID)
)

/*게시물*/
CREATE TABLE POST(
	POST_NO VARCHAR2(4000) PRIMARY KEY,
	ID VARCHAR2(4000),
	CONSTRAINT POST_ID_FK FOREIGN KEY(ID) 
	REFERENCES MEMBER(ID) ON DELETE CASCADE,
	COMMENTS CLOB NOT NULL,
	REGISTER_DATE DATE DEFAULT SYSDATE
)

CREATE SEQUENCE POST_SEQ NOCACHE

/*게시물 사진*/
CREATE TABLE POST_PIC(
	PIC_NO VARCHAR2(4000) PRIMARY KEY,
	POST_NO VARCHAR2(4000),
	CONSTRAINT POST_PIC_NO_FK FOREIGN KEY(POST_NO)
	REFERENCES POST(POST_NO) ON DELETE CASCADE,
	PIC VARCHAR2(4000) NOT NULL
)
CREATE SEQUENCE POST_PIC_SEQ NOCACHE

select * from POST_PIC